### PR TITLE
Fixes arccos evaluating double close to -1 or 1

### LINKED ISSUE #4393: Unexpected "nan" in caminfo output
**ISIS version(s) affected**: >=3.10.2 

**Description**  
`caminfo` produces values of "nan" for the `SubSpacecraftGroundAzimuth`, `ParallaxX`, and `ParallaxY` keywords on certain images, even though `caminfo` is still able to compute other angles and even project a footprint onto the target body. I have only found this to affect specific MOC EDRs, THEMIS IR EDRs, and THEMIS VIS EDRs.

**How to reproduce**  
```
moc2isis/thm2isis from=infile to=outfile.cub    #program depends on which image being input, obvs 
spiceinit from=outfile.cub
caminfo from=outfile.cub to=outfile_caminfo.pvl geometry=yes isislabel=yes statistics=yes camstats=yes polygon=yes inctype=vertices numvertices=40

grep "nan" outfile_caminfo.pvl
#    SubSpacecraftGroundAzimuth = nan
#    ParallaxX                  = nan
#    ParallaxY                  = nan

```

**Additional context**  
Complete list of the affected images:
[/pds_san/PDS_Archive/Mars_Global_Surveyor/MOC/mgsc_1029/m03003/m0300359.imq](https://pdsimage.wr.usgs.gov/Missions/Mars_Global_Surveyor/MOC/mgsc_1029/m03003/m0300359.imq)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10066/data/odtie1_0066/r723xxedr/R72340029EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10066/data/odtie1_0066/r723xxedr/R72340029EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10071/data/odtie1_0071/r782xxedr/R78241001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10071/data/odtie1_0071/r782xxedr/R78241001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10009/data/odtie1_0009/r094xxedr/R09436025EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10009/data/odtie1_0009/r094xxedr/R09436025EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10008/data/odtve1_0008/v080xxedr/V08090001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10008/data/odtve1_0008/v080xxedr/V08090001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10011/data/odtve1_0011/v121xxedr/V12120008EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10011/data/odtve1_0011/v121xxedr/V12120008EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10014/data/odtve1_0014/v148xxedr/V14802004EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10014/data/odtve1_0014/v148xxedr/V14802004EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v183xxedr/V18386001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v183xxedr/V18386001EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v187xxedr/V18763010EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10017/data/odtve1_0017/v187xxedr/V18763010EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10022/data/odtve1_0022/v236xxedr/V23662019EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10022/data/odtve1_0022/v236xxedr/V23662019EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v263xxedr/V26315022EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v263xxedr/V26315022EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v267xxedr/V26737030EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10024/data/odtve1_0024/v267xxedr/V26737030EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10026/data/odtve1_0026/v280xxedr/V28061017EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10026/data/odtve1_0026/v280xxedr/V28061017EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10030/data/odtve1_0030/v327xxedr/V32776005EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10030/data/odtve1_0030/v327xxedr/V32776005EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10033/data/odtve1_0033/v365xxedr/V36572024EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10033/data/odtve1_0033/v365xxedr/V36572024EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10036/data/odtve1_0036/v399xxedr/V39981004EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10036/data/odtve1_0036/v399xxedr/V39981004EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v457xxedr/V45719019EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v457xxedr/V45719019EDR.QUB)
[/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v463xxedr/V46394001EDR.QUB](https://pdsimage.wr.usgs.gov/Missions/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10042/data/odtve1_0042/v463xxedr/V46394001EDR.QUB)

### PR DESCRIPTION
**Pull request by acpaquette**
Fixed issue where the acos of -1.0000000001 was resulting in a nan

## Description
Fixes an issue in caminfo where we apply arccos to another trigonometric expression that results in a double. Sometimes the result should be -1 or 1 but due to double precision accuracy it results in something extremely close to those values eg. `acos(-1.000000000001)`. This is an inelegant solution but solves the problem in caminfo.

## Related Issue
Closes #4393

## Motivation and Context
ISIS 5.0.1 Support Sprint

## How Has This Been Tested?
Tested manually through caminfo/campt

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/base/objs/Camera/Camera.cpp [hunk 1]
```diff
@@ -2303,7 +2303,14 @@ namespace Isis {
     if (sin(b) == 0.0 || sin(c) == 0.0) {
       return azimuth;
     }
-    double A = acos((cos(a) - cos(b)*cos(c))/(sin(b)*sin(c))) * 180.0 / PI;
+    double intermitent = (cos(a) - cos(b)*cos(c))/(sin(b)*sin(c));
```
Comment (dpmayerUSGS) [inline isis/src/base/objs/Camera/Camera.cpp]: Correct spelling is "intermittent."

The word "intermittent" means "sporadic" or "occasional." The mathematical expression simply defines what will become the argument to acos(). Consider using a different name that more closely describes the expression.

**Review by dpmayerUSGS — CHANGES_REQUESTED** [review]

File: isis/src/base/objs/Camera/Camera.cpp (hunk 1 above)
Comment (acpaquette) [reply isis/src/base/objs/Camera/Camera.cpp]: Updated to `intermediate`. I think that was what I wanted original just crossed wires in my brain

Comment (dpmayerUSGS) [reply isis/src/base/objs/Camera/Camera.cpp]: No worries, it happens.

**Review by dpmayerUSGS — DISMISSED** [review]
`intermediate` sounds good to me as a variable name. The if/else logic to clamp intermediate values within the [-1,1] interval looks correct to me.

**Review by dpmayerUSGS — APPROVED** [review]

**Review by jessemapel — APPROVED** [review]
