### PR TITLE
Fixed jigsaw residual reporting in bundleout.txt

### LINKED ISSUE #4655: Jigsaw - Residual Percentiles have changed
**ISIS version(s) affected**: 6.0.0

**Description**  
The Residual Percentiles and Residual Box Plot in the bundleout.txt file has dramatically changed from the last version of isis.

**How to reproduce**  
Compare all output from isis5.0.2 jigsaw to all output from isis6.0.0.  I don't think the type of solution matters as I saw this while solving for camera accelerations via Kaguya TC, but tested on a smaller Themis IR data set solving for camera and spacecraft with errorprop turned on (re-using old test data).  The only difference in the isis5.0.2 and isis6.0.0 output (including output network files) was the Residual Percentiles/Box Plot reported under isis6.0.0 are very much larger than what is reported in isis5.0.2 and don't correlate with what is reported in the residuals.csv file.

There is a small test network under /work/users/lweller/Isis3Tests/Jigsaw/Percentiles/.  See proc.scr to see command lines for both versions of isis as well as the diff tests run.  Note that the images in the input jigsaw fromlist reside in another directory.

Since it's small enough, here are the Residual Box Plot differences in the two runs (I've omitted the lengthier Percentiles output here):
```
diff isis5.0.2_bundleout.txt isis6.0.0_bundleout.txt
<                         minimum:   -1.204
<                      Quartile 1:   -0.110
<                          Median:   -0.001
<                      Quartile 3:   +0.103
<                         maximum:   +1.490
---
>                         minimum:  -17.194
>                      Quartile 1:   -1.576
>                          Median:   -0.010
>                      Quartile 3:   +1.469
>                         maximum:  +21.281
```

The maximum residual in residuals.csv is 1.8 so the isis5.0.2 output makes better sense.

Note that this output is not useful or even relevant to me - I'm simply reporting a bug.  I just happened to notice how large the values were when I was scrolling through a bundleout file having just seen my maximum residual was less than 2 (the min/max box plot values where >900 for my much larger Kaugya TC data set then the test data I provided and reported on above).

Although the test case above touches a few different parameters, I don't know if there are other differences in the isis versions other what's reported.  It's possible something else differs for say multi- sensor solutions.  I'm just suggesting I haven't exhausted the possibilities.

### PR DESCRIPTION
**Pull request by jessemapel**
## Description

Fixed how residuals are re-scaled when reporting to the bundelout.txt file.

## Related Issue

Fixes #4655 

## Motivation and Context

This gets the bundleout.txt file in line with the residuals csv.

## How Has This Been Tested?

Tested on an example network I have and added an automated check in a jigsaw gtest.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp [hunk 1]
```diff
@@ -1368,8 +1368,7 @@ QStringList IsisBundleObservation::parameterList() {
    *                calculated (line, sample) coordinate
    */
   double IsisBundleObservation::computeObservationValue(BundleMeasure &measure, double deltaVal) {
-    Camera *measureCamera = measure.camera();
-    return deltaVal / measureCamera->PixelPitch();
+    return deltaVal * 1.4;
```
Comment (acpaquette) [inline isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp:1371]: Seems like a bit of a magic number here, could we get some kind of comment as to why this is 1.4?

**Review by acpaquette — COMMENTED** [review]
Overall looks good, only other thing is that a change log entry could be added to IsisBundleObservation.h

File: isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp (hunk 1 above)
Comment (KrisBecker) [reply isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp:1371]: This looks suspiciously like std::sqrt(2.0), which is the distance from the center of a square pixel to any one of its corners. The returned value is in pixel units rather than physical size (mm?) of the detector pixel.

Comment (jessemapel) [reply isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp:1371]: Kris is correct that it's a shortcut for sqrt(2). This is porting some old logic over so if 1.4 should be used is a bit beyond this PR. See my post on the issue:

https://github.com/USGS-Astrogeology/ISIS3/issues/4655#issuecomment-944361620

Because we don't actually need to be modeling the physical reality of anything, we just need a mathematically consistent system using 1.4 is totally fine as long as it's consistent. In an ideal world, this bit would be completely obsoleted by actual measure weighting but we haven't implemented a good way to do that yet; so, we're just waiting on a sensor by sensor basis.

**Comment by jessemapel** [comment]
I usually do not add @history tags to docs that don't already have them. @acpaquette Is there a reason why this should get one?

**Review by acpaquette — APPROVED** [review]
@jessemapel Did not check if that file had a history tag in the label so my previous comment can be ignored

**Review by acpaquette — APPROVED** [review]
