### PR TITLE
hideal2pds #3978 fix

### LINKED ISSUE #3978: hideal2pds outputs incorrect value of SAMPLE_BIT_MASK in label for all but 16 bit compression
**ISIS version(s) affected**: 3.9.0

**Description**  
With hideal2pds, when selecting any bit compression other than 16, the SAMPLE_BIT_MASK in the output label is incorrect. Below is an excerpt from an output label where bit=10 was selected.
[...
OBJECT = IMAGE
  DESCRIPTION                = "HiRISE mosaicked product, not map projected"
  LINES                      = 2500
  LINE_SAMPLES               = 5000
  SOURCE_LINE_SAMPLES        = 5000.0
  SOURCE_LINES               = 2500.0
  FIRST_LINE_SAMPLE          = 0.5
  FIRST_LINE                 = 0.5
  BANDS                      = 1
  OFFSET                     = 0.0037222964252952
  SCALING_FACTOR             = 3.14850405127014e-06
  SAMPLE_BITS                = 16
  SAMPLE_BIT_MASK            = 2#1111111111111111#
  SAMPLE_TYPE                = MSB_UNSIGNED_INTEGER
  FILTER_NAME                = "Red"
  CENTER_FILTER_WAVELENGTH   = 700 <NM>
  BAND_WIDTH                 = 300 <NM>
  BAND_STORAGE_TYPE          = BAND_SEQUENTIAL
  CORE_NULL                  = 0
  CORE_LOW_REPR_SATURATION   = 1
  CORE_LOW_INSTR_SATURATION  = 2
  CORE_HIGH_REPR_SATURATION  = 1023
  CORE_HIGH_INSTR_SATURATION = 1022
END_OBJECT = IMAGE
...]

Should be:
`SAMPLE_BIT_MASK 2#0000001111111111#`

**How to reproduce**  
hideal2pds max=0.006936919061642 to=ESP_057858_1410_RED.NOPROJ.img type=MANUAL version=1.0 min=0.003731741937449 from=PSP_009492_1280_RED.NOPROJ.cub bits=10

**Possible Solution**  

**Additional context**  
[PSP_009492_1280_RED.NOPROJ.lbl.gz](https://github.com/USGS-Astrogeology/ISIS3/files/5104979/PSP_009492_1280_RED.NOPROJ.lbl.gz)
[PSP_009492_1280_RED.NOPROJ.cub.gz](https://github.com/USGS-Astrogeology/ISIS3/files/5104990/PSP_009492_1280_RED.NOPROJ.cub.gz)

### PR DESCRIPTION
**Pull request by tgiroux**
## Description

Before these changes, hideal2pds writes SAMPLE_BIT_MASK = 2#1111111111111111# by default for all cases. These few added lines write the correct value of SAMPLE_BIT_MASK to the output label as intended. This could not take place within updatePdsLabelImageObject() because it requires access to user input for the BITS field, so I put it directly afterwards.
Truth data will need to be updated following a merge of this PR to account for the change of expected output from hideal2pds.

## Related Issue

Fixes #3978

## Motivation and Context

hideal2pds previously outputted an incorrect label for all but 16 bit compression. User had to manually correct the SAMPLE_BIT_MASK value in the label in order to move forward.

## How Has This Been Tested?

Tested using `$make checkout` `$make output` and viewing the output pvl files to assure that the correct values were produced.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [AUTHORS.rst](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/AUTHORS.rst) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/mro/apps/hideal2pds/main.cpp [hunk 1]
```diff
@@ -184,6 +184,12 @@ void IsisMain() {
 
   updatePdsLabelTimeParametersGroup(pdsLabel);
   updatePdsLabelImageObject(isisCubeLab, pdsLabel);
+  if (nbits >= 8 && nbits < 16) {
```
Comment (scsides) [inline isis/src/mro/apps/hideal2pds/main.cpp]: Why the logic change from the other apps that do this (!=8 or 16)? Does this fix the 8 bit issue you found?

**Review by scsides — CHANGES_REQUESTED** [review]
Just one question

**Comment by krlberry** [comment]
Could you also add an item to the new changelog for this change? See PR #4000 for an example.

**Comment by jessemapel** [comment]
@tgiroux Couple little process notes. Make sure you use "x" for checkboxes. `[x]` will render properly, but `[*]` won't. Also, use fixes #blah under the related issue if your PR fixes it, that will trigger github to auto-close on PR merge.

File: isis/src/mro/apps/hideal2pds/main.cpp (hunk 1 above)
Comment (tgiroux) [reply isis/src/mro/apps/hideal2pds/main.cpp]: I removed the if statement. For nbits==8, it was necessary to explicitly write SAMPLE_BIT_MASK as 2**8-1 in order for the correctly write an 8 bit value to the output label. For nbits=16, it is not necessary to explicitly write SAMPLE_BIT_MASK (it resolves to the correct value without this added bit of code), but I figured it may be appropriate to do so explicitly for the sake of consistency / readability.

**Review by scsides — CHANGES_REQUESTED** [review]
Deleted

**Review by scsides — APPROVED** [review]
Looks good

**Review by scsides — DISMISSED** [review]

**Review by scsides — APPROVED** [review]
