### PR TITLE
Fixed Cube::fromIsd to add "LineScanTimes" table from HRSC isds

### LINKED ISSUE #5668: Cube::fromIsd doesn't add LineScanTimes table for HRSC Isds
I tried to create an HRSC camera fixture with an ISD but ran into errors that the camera model could not find the LineScanTimes table. Looks like Cube::fromIsd only adds Spice table data and not any additional tables that may be in the ISD.

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Related Issue

closes #5668 

## How Has This Been Validated?

Added test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/mex/objs/HrscCamera/HrscCamera.cpp [hunk 1]
```diff
@@ -119,14 +119,22 @@ namespace Isis {
...
+   * @param cube
    */
-  void HrscCamera::ReadLineRates(QString filename) {
-    Table timesTable("LineScanTimes", filename);
+  void HrscCamera::ReadLineRates(Cube &cube) {
+    Table timesTable("LineScanTimes");
+
+    // check if LineScanTimes was added from isd
+    if (cube.hasTable("LineScanTimes")) {
+      timesTable = cube.readTable("LineScanTimes");
```
Comment (acpaquette) [inline isis/src/mex/objs/HrscCamera/HrscCamera.cpp]: Can use this line in both cases?

File: isis/src/base/objs/Cube/Cube.cpp [hunk 2]
```diff
@@ -98,6 +98,10 @@ namespace Isis {
    */
   void Cube::fromIsd(const FileName &fileName, Pvl &label, nlohmann::json &isd, QString access) {
     fromLabel(fileName, label, access);
+
+    if (isd.contains("line_scan_rate")) {
+      attachLineScanTableFromIsd(isd);
+    }
```
Comment (acpaquette) [inline isis/src/base/objs/Cube/Cube.cpp]: I am a little worried that this attaches the ```line_scan_rate``` from any ISD. All of our line scanner ISDs have the attribute

**Review by acpaquette — COMMENTED** [review]
Overall looks good! Just a couple comments to address

File: isis/src/mex/objs/HrscCamera/HrscCamera.cpp (hunk 1 above)
Comment (amystamile-usgs) [reply isis/src/mex/objs/HrscCamera/HrscCamera.cpp]: Yeah I think you're right. This has been updated.

File: isis/src/base/objs/Cube/Cube.cpp (hunk 2 above)
Comment (amystamile-usgs) [reply isis/src/base/objs/Cube/Cube.cpp]: True. Updated check.

**Review by acpaquette — APPROVED** [review]
