### PR TITLE
App Fixes For GeoTiffs

### LINKED ISSUE #5842: Spiceinit web fails with geotiffs
**ISIS version(s) affected**: x.y.z

**Description**  

When using a GTIFF to spiceinit, I get an error from the server: 

```bash
(isisqlarm4) igswza281l2305:ISIS krodriguez$ ../isisbuild/bin/spiceinit from=/Users/krodriguez/cubes/FC21B0001010_09049002212F5D.tiff web=True shape=Ellipsoid
**ERROR** An error occurred when talking to the server. The server encountered an unexpected error.
```

**How to reproduce**  

convert a cube to GTIFF with cubeatt and then spiceinit it with web=true

**Possible Solution**  

I imagine the label is not being sent correctly over the network it there is a bug in attaching the returned spice tables. 

**Additional context**

### LINKED ISSUE #5869: weird csminit behavior with GTIFFs
**ISIS version(s) affected**: dev

**Description**  

csminit-ing with a GTIFFs gives: 

```
(isisbuilds) ch2nettests krodriguez$ csminit from=ch2_tmc_nca_20200203T0658276879_d_img_d18.tiff isd=ch2_tmc_nca_20200203T0658276879_d_img_d18.json
**ERROR** Failed to create a CSMCamera.
**ERROR** Unable to initialize camera model in Camera Factory.
**ERROR** Unable to locate latest camera model version number from group [Instrument].
**ERROR** Unsupported camera model, unable to find plugin for SpacecraftName [CHANDRAYAAN-2] with InstrumentId [TMC-2].
**ERROR** Unable to find PVL group [CHANDRAYAAN-2/TMC-2].
```

However, csminit-ing and then coverting to gtiff works fine.  

```bash
(isisbuilds) igswza281l2305:cubes krodriguez$ campt from=ch2_tmc_nca_20200207T0716469418_d_img_d18.tiff
Group = GroundPoint
  Filename                   = ch2_tmc_nca_20200207T0716469418_d_img_d18.tiff
  Sample                     = 2000.0
  Line                       = 90026.5
  PixelValue                 = 133
  RightAscension             = 159.07897535825 <DEGREE>
  Declination                = -8.6511588976135 <DEGREE>
  PlanetocentricLatitude     = -17.699283527776 <DEGREE>
...
```

**How to reproduce**  

Ingest a CH-2 TMC2 image using ISIS import, use cubeatt to convert into a GTIFF, then try to csminit the tiff. Might be replicable with any instrument, not just TMC2.

**Possible Solution**  

I imagine something is not propagating through the labels correctly, or more likely, it is failing to write the blob and the errors are a red herring. 

**Additional context**

### PR DESCRIPTION
**Pull request by acpaquette**
## Description
Fixes apps that fail when passing a GeoTiff with ISIS metadata

## Related Issue

Fixes #5842
Fixes #5869 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
I imagine the CH-2 test failures are unrelated.

Spiceinit on a GTIFF was fine. 

CSMINIT gave an error 

```
(isisgdalbuilds) igswza281l2305:isisbuild krodriguez$ ./bin/csminit from=~/cnets/I52634011RDR.tiff isd=~/cnets/I52634011RDR.json
**USER ERROR** No loaded model could be created from the ISD [/Users/krodriguez/cnets/I52634011RDR.json].Loaded plugin & model names:
Plugin [UsgsAstroPluginCSM], Model [USGS_ASTRO_FRAME_SENSOR_MODEL]
.
.
.
```

**Comment by Kelvinrr** [comment]
Problem seems to be from an unrelated bug.

**Comment by Kelvinrr** [comment]
Looks good, needs a changlog entry.

File: isis/src/base/objs/Cube/Cube.cpp [hunk 1]
```diff
@@ -808,27 +808,26 @@ namespace Isis {
...
-        cleanUp(false);
-        exceptions.append(e);
-      }
+
+    GDALDriverH hDriver = GDALIdentifyDriver(FileName(cubeFileName).expanded().toStdString().c_str(), nullptr);
+    bool openWithGdal = false;
+    if (hDriver != nullptr) {
+        GDALDriver* poDriver = (GDALDriver*)hDriver;
+        QString driverDescription = poDriver->GetDescription();
+        openWithGdal = driverDescription == QString("GTiff");
```
Comment (Kelvinrr) [inline isis/src/base/objs/Cube/Cube.cpp]: Theoritically, with GDAL 3.12, could we GDAL translate to a PNG (or any other non-cube raster format) and still read in ISIS?

Comment (acpaquette) [reply isis/src/base/objs/Cube/Cube.cpp]: I reversed this, so instead of checking for a gtiff it now checks if the driver is not the "ISIS3" driver. So we will try to open it using the gdal control flow if it isn't an ISIS3 cube.

**Review by Kelvinrr — APPROVED** [review]
