### PR TITLE
manually added oglab onto HRSC stereo images, removed unsued functions in hrsc2isis

### LINKED ISSUE #4816: hrsc2isis does not propagate original label to output for summed images
**ISIS version(s) affected**: 5.0.2

**Description**  
catoriglab fails for HRSC CCD line detector images which contain the keyword MACROPIXEL_SIZE in the IMG file which is translated to the Summing keyword when ingested into ISIS.  These are images having Detector Id's similar to MEX_HRSC_NADIR and MEX_HRSC_RED and so on.

On the other hand, catoriglab run successfully for HRSC SRC images which do not contain the MACROPIXEL_SIZE in the IMG file and no Summing keyword in the isis cube upon ingestion. These are images having DETECTOR_ID = MEX_HRSC_SRC.

**How to reproduce**  
See data (IMG and isis cubes) under /work/users/lweller/Isis3Tests/CatOrigLab/.

catoriglab from=H0756_0000_ND2.lev0.cub to=ND2_lab.pvl
```
  Group = Error
    Program = catoriglab
    Class   = "USER ERROR"
    Code    = 2
    Message = "Could not find OriginalLabel or OriginalXmlLabel in input file
               [H0756_0000_ND2.lev0.cub]"
    File    = main.cpp
    Line    = 81
  End_Group
```
H0756_0000_RE2.lev0.cub in the same directory produces similar results.

The SRC image H0748_0003_SR2.lev0.cub will run successfully:
`catoriglab from=H0748_0003_SR2.lev0.cub to=SR2_lab.pvl`

**Additional context**  
Oddly, caminfo runs without errors or warnings when originallabel=true when passing it one of the HRSC CCD line detector images but there is no original label information in the output file.  I think that is also bug and will report that in another post.

### PR DESCRIPTION
**Pull request by Kelvinrr**
## Description

`hrsc2isis` has two different functions for processing PDS image, stereo vs non-stereo, the latter created an empty cube rather than letting the Process object handle creating the cube, as such `ProcessImportPds::Finalize()` was never called on the output cube which is where the original PDS label would have been attached. 

Also removed some redundant functions in hrsc2isis.cpp that were not being used. 

## Related Issue

closes https://github.com/USGS-Astrogeology/ISIS3/issues/4816

## Motivation and Context

Depending on the `DETECTOR_ID` on the input HRSC image, the original PDS labels were not attached. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/mex/apps/hrsc2isis/hrsc2isis.cpp [hunk 1]
```diff
@@ -15,12 +15,11 @@ find files of those names at the top level of this repository. **/
 #include "LineManager.h"
 #include "IException.h"
 #include "Application.h"
+#include "OriginalLabel.h"
 
 using namespace std;
 namespace Isis{
-  void ImportHrscStereoImage(ProcessImportPds &p, Pvl &label);
-  void ImportHrscStereoImage(ProcessImportPds &p, Pvl &label, UserInterface &ui);
-  void ImportHrscSrcImage(ProcessImportPds &p, Pvl &label);
```
Comment (Kelvinrr) [inline isis/src/mex/apps/hrsc2isis/hrsc2isis.cpp:23]: The non UI versions were not really used, or rather, the UI version was used for stereo but not for non-stereo which meant output atts were not applied depending on detector ID as well. Figure I'd normalize them and only use the versions with UI as the input and apply out attrs to both.

**Review by jessemapel — COMMENTED** [review]
Add a changelog entry for the bug fix and a check in the test that it properly adds the original label. Code changes look good.

**Review by jessemapel — APPROVED** [review]
