### PR TITLE
gllssi2isis Original Label Fix

### LINKED ISSUE #3207: gllssi2isis does not create/store OriginalLabel properly for summed images
**ISIS version(s) affected**: 3.6.2

**Description**  
The ingestion application gllssi2isis does not appear to be storing the original pds label information properly.  The program appears to run successfully and many other applications applied to the ingested data don't have problems (spiceinit, gllssical, footprintinint, etc.), however, caminfo (using originallabel=true) will fail on these images as does catoriglab with the messages saying the OriginalLabel could not be opened or found (see details below).

This affects 174 of my Galileo Europa images (25% of the data).

**How to reproduce**  
Data used below available here: /work/users/lweller/Isis3Tests/Gllssi2isis/
I thought it would be easier to have the pds data locally, but if you need original location information, let me know.

Ingest a summed image using gllssi2isis then run catoriglab or caminfo to get an error:

gllssi2isis from=9825r.lbl to=9825r.cub

catoriglab from=9825r.cub to=origlbl_9825r.pvl

    Program = catoriglab
    Class   = "USER ERROR"
    Code    = 2
    Message = "Could not find OriginalLabel or OriginalXmlLabel in input file
               [9825r.cub]"
    File    = catoriglab.cpp
    Line    = 81

Here is the error from caminfo since it might be slightly more helpful:

    Program = caminfo
    Class   = "I/O ERROR"
    Code    = 4
    Message = "Unable to open OriginalLabel [IsisCube] in file [9825r.cub]"
    File    = Blob.cpp
    Line    = 289

Image 7765r is provided as an example of a full frame (unsummed) image that appears to have its original label information stored properly (output from catoriglab is origlab_7765r.pvl).

I ran both images in the directory through ingestion, spiceinit and footprintinit.

I don't see anything about summing mode in the pds lbl files, but full frame images are 800x800 and summed images are 400x400 samples and lines.

**Possible Solution**  
Handle images having summing=2 properly.

**Additional context**  
I originally ran into this problem while running caminfo with the settings "isislabel=true geometry=true originallabel=true statistics=true camstats=true linc=10 sinc=10 uselabel=true".  I use all of this output to populate a database for image selection and overlap information.  Although there a few original label keywords I would like access to (we don't propagate them to the isis label upon ingestion), the polygon information is critical and it appears I can get that information for summing mode 2 images by setting originallabel=false.  So I have a work around for the most important information.

A side note - this ingestion bug and subsequent problems with caminfo may explain why there are so many "unmapped" Galileo SSI images on PILOT (FYI @USGSsakins).  I looked at some of the info files for the unmapped images that were also in my failure list and they say "Error running caminfo on file". 
 Anyway, fixing this bug would likely help PILOT serve more Galileo SSI images of Europa to the public (and possible some other bothers as well).

Please let me know if you have questions or if I left something critical out of my description.

### PR DESCRIPTION
**Pull request by acpaquette**
Fixes the gllssi2isis to output the original label if the ingestion app is using its "summing" mode. 

## Description
Updated setOutputCube in ProcessImport to expose more parameters when accessing Process's setOutputCube function. Specifically, the new "base" setOutputCube methods allows for custom attribute object, number of samples, lines, and bands. The old method just default to this new methods with the appropriate parameters passed in.

## Related Issue
Fixes #3207.

## Motivation and Context
The old label is required in some ISIS applications. Attaching the original labels to these ingested cubes will allow those cubes to be used in the ISIS applications that require the original label.

## How Has This Been Tested?
Tested using a test that already exists in the system. Test will need to be updated as the pvl output of the cube label will change since it now has the original label.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [X] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 1]
```diff
@@ -110,22 +109,16 @@ void IsisMain() {
...
+    p.StartProcess(translateData);
   }
 
   translateLabels(pdsLabel, ocube);
   p.EndProcess();
 
-  if (summed) {
-    summedOutput->close();
-    delete summedOutput;
-  }
```
Comment (SgStapleton) [inline isis/src/galileo/apps/gllssi2isis/main.cpp]: Do we not still need to delete the summedOutput?

Comment (acpaquette) [reply isis/src/galileo/apps/gllssi2isis/main.cpp]: This is handled by the ClearOutputCubes method in the Process class. Once EndProcess is called if you follow the call stack, all the cubes are closed and deleted.

File: isis/src/base/objs/ProcessImport/ProcessImport.cpp [hunk 2]
```diff
@@ -1199,21 +1199,26 @@ namespace Isis {
...
+   *
    * @return @b Isis::Cube Output cube.
    *
    * @throws Isis::iException::Message "Unsupported pixel type."
    */
-  Isis::Cube *ProcessImport::SetOutputCube(const QString &parameter) {
-    CubeAttributeOutput &att =
-      Application::GetUserInterface().GetOutputAttribute(parameter);
-
+  Isis::Cube *ProcessImport::SetOutputCube(const QString &parameter, CubeAttributeOutput &att, const int ns, const int nl, const int nb) {
```
Comment (scsides) [inline isis/src/base/objs/ProcessImport/ProcessImport.cpp]: Since this call is being passed the user interface parameter name, I don't see the reason to pass in the CubeAttribute. It is part of what the user typed. Also, the original SetOutputCube member parsed the value of the parameter and pulled the attributes off in order to call the parents member. Seems reasonable to continue doing this and not make the application programmer do this.

Comment (jessemapel) [inline isis/src/base/objs/ProcessImport/ProcessImport.cpp]: Why add a whole separate method? Can't you just call SetDimensions and then call the old SetOutputCube?

File: isis/src/base/objs/ProcessImport/ProcessImport.h [hunk 3]
```diff
@@ -163,9 +163,11 @@ namespace Isis {
    *                           was made to accomodate Rosetta VIRTIS-m calibrated data files and
    *                           has no impact on other supported BIP files.
    *                           Fixes #5398.
-   *   @history 208-07-19 Tyler Wilson - Added support for 4-byte UnsignedInteger special pixel
+   *   @history 2018-07-19 Tyler Wilson - Added support for 4-byte UnsignedInteger special pixel
    *                            values.
-   *
+   *   @history 2019-04-15 Adam Paquette - Exposed the ns, nl, nb (number of samples, lines, and bands)
+   *                           for the setOutputCube function. Updated existing setOutputCube methods
```
Comment (scsides) [inline isis/src/base/objs/ProcessImport/ProcessImport.h]: Exposed by adding a new SetOutputCube member

**Review by scsides — CHANGES_REQUESTED** [review]
See individual comments

File: isis/src/base/objs/ProcessImport/ProcessImport.h (hunk 3 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.h]: :+1:

File: isis/src/base/objs/ProcessImport/ProcessImport.cpp (hunk 2 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.cpp]: Probably, I saw the setDimension function this morning so I will mess around with it.

File: isis/src/galileo/apps/gllssi2isis/main.cpp (hunk 1 above)
Comment (SgStapleton) [reply isis/src/galileo/apps/gllssi2isis/main.cpp]: :+1:

File: isis/src/base/objs/ProcessImport/ProcessImport.cpp (hunk 2 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.cpp]: Yup, worked like a charm :+1:

File: isis/src/base/objs/ProcessImport/ProcessImport.h [hunk 4]
```diff
@@ -163,11 +163,9 @@ namespace Isis {
    *                           was made to accomodate Rosetta VIRTIS-m calibrated data files and
    *                           has no impact on other supported BIP files.
    *                           Fixes #5398.
-   *   @history 2018-07-19 Tyler Wilson - Added support for 4-byte UnsignedInteger special pixel
+   *   @history 208-07-19 Tyler Wilson - Added support for 4-byte UnsignedInteger special pixel
```
Comment (jlaura) [inline isis/src/base/objs/ProcessImport/ProcessImport.h]: ?

File: isis/src/base/objs/ProcessImport/ProcessImport.h (hunk 3 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.h]: No longer necessary as the change to ProcessImport was unnecessary

File: isis/src/base/objs/ProcessImport/ProcessImport.h (hunk 4 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.h]: Was removed due to me clobbering the changes I had made to the ProcessImport files. WIll re-add

Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.h]: :+1:

File: isis/src/base/objs/ProcessImport/ProcessImport.cpp (hunk 2 above)
Comment (acpaquette) [reply isis/src/base/objs/ProcessImport/ProcessImport.cpp]: No longer necessary as the change to ProcessImport was unnecessary

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 5]
```diff
@@ -110,22 +109,15 @@ void IsisMain() {
...
   }
   else {
-    summedOutput = new Cube();
-    summedOutput->setDimensions(p.Samples() / 2, p.Lines() / 2, p.Bands());
-    summedOutput->setPixelType(p.PixelType());
-    summedOutput->create(ui.GetFileName("TO"));
-    p.StartProcess(translateData);
+    p.SetDimensions(p.Samples() / 2, p.Lines() / 2, p.Bands());
+    summedOutput = p.SetOutputCube("TO");
     ocube = summedOutput;
```
Comment (SgStapleton) [inline isis/src/galileo/apps/gllssi2isis/main.cpp]: ocube = p.SetOutputCube("TO");    ?

Do we need summedOutput now...?

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 6]
```diff
@@ -110,22 +109,15 @@ void IsisMain() {
     p.StartProcess();
   }
   else {
-    summedOutput = new Cube();
-    summedOutput->setDimensions(p.Samples() / 2, p.Lines() / 2, p.Bands());
-    summedOutput->setPixelType(p.PixelType());
-    summedOutput->create(ui.GetFileName("TO"));
-    p.StartProcess(translateData);
+    p.SetDimensions(p.Samples() / 2, p.Lines() / 2, p.Bands());
+    summedOutput = p.SetOutputCube("TO");
```
Comment (SgStapleton) [inline isis/src/galileo/apps/gllssi2isis/main.cpp]: ocube = p.SetOutputCube("TO"); ?

Do we need summedOutput now...?

Comment (SgStapleton) [reply isis/src/galileo/apps/gllssi2isis/main.cpp]: I just noticed that summedOutput is being used further down. Is that why we still need to instantiate it here?

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 7]
```diff
@@ -182,7 +174,7 @@ void fixPvl(QString fileName){
 
 
 
-void translateData(Buffer &inData) {
+void translateData(Isis::Buffer &inData) {
   summedOutput->write(inData);
```
Comment (SgStapleton) [inline isis/src/galileo/apps/gllssi2isis/main.cpp:166]: Could this be replaced with ocube to get rid of summedOutput altogether?

**Comment by acpaquette** [comment]
Apologies with the drastic changes that are happening between commits :grimacing:

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 8]
```diff
@@ -28,25 +26,19 @@ void translateLabels(Pvl &pdsLabel, Cube *ocube);
...
   summed = false;
   summedOutput = NULL;
   // Grab the file to import
   ProcessImportPds p;
   UserInterface &ui = Application::GetUserInterface();
   FileName inFile = ui.GetFileName("FROM");
-  FileName out = ui.GetFileName("TO");
-
-
+  FileName outFile = ui.GetFileName("TO");
```
Comment (scsides) [inline isis/src/galileo/apps/gllssi2isis/main.cpp:36]: Is this used anywhere?

**Review by scsides — DISMISSED** [review]

File: isis/src/galileo/apps/gllssi2isis/main.cpp (hunk 8 above)
Comment (acpaquette) [reply isis/src/galileo/apps/gllssi2isis/main.cpp:36]: Will make a change to use it

File: isis/src/galileo/apps/gllssi2isis/main.cpp [hunk 9]
```diff
@@ -102,35 +94,34 @@ void IsisMain() {
...
   p.SetPdsFile(inFile.expanded(), "", pdsLabel);
 
-  //Set up the output file
-  Cube *ocube;
-
+  // If summed handle the image similarly to pds2isis
+  // with an extra translation step
   if (!summed) {
-    ocube = p.SetOutputCube("TO");
+    Cube *ocube = p.SetOutputCube("TO");
```
Comment (jessemapel) [inline isis/src/galileo/apps/gllssi2isis/main.cpp]: Does ProcessImport pass ownership or does it delete this when EndProcess is called?

**Review by scsides — APPROVED** [review]
