### PR TITLE
Update tgocassis2isis, tgocassisrdrgen, and add an application to mosaic CaSSIS images, and fix problems with CaSSIS distortion model. Fixes #5418, #5417, #5265

### LINKED ISSUE #5418: "unable to write session log"
tparker$ pds2isis                                                                                                  
**WARNING** Unable to write session log [print.prt] Disk may be full or directory permissions not writeable 

I've checked and have read and write permissions on all my devices and folders with CTX data downloaded from the PDS.

### PR DESCRIPTION
**Pull request by jcwbacker**

### CODE REVIEW

File: isis/src/base/apps/isis2pds/isis2pds.cpp [hunk 1]
```diff
@@ -184,6 +193,7 @@ void IsisMain() {
     Application::Log(results);
 
     process.StandardPds4Label();
+//    ProcessExportPds4::translateUnits(pdsLabel);//???
```
Comment (krlberry) [inline isis/src/base/apps/isis2pds/isis2pds.cpp]: Potentially remove this added comment?

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp [hunk 2]
```diff
@@ -82,76 +89,102 @@ namespace Isis {
...
+    translateUnits(*m_domDoc);
+    return *m_domDoc;
+  }
 
-      CreateImageLabel();
-      translateUnits(*m_domDoc);
-      return *m_domDoc;
-    }
+
+    /**
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp]: not lined up with other asterisks in comment (very nitpicky)

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp [hunk 3]
```diff
@@ -273,9 +388,9 @@ namespace Isis {
   void ProcessExportPds4::displaySettings() {
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp:388]: Add documentation

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp [hunk 4]
```diff
@@ -291,35 +406,281 @@ namespace Isis {
...
+        translateBandBinSpectrumBinSet(*inputLabel);
+      }
+    }
+  }
+
 
-    FileName transfile;
-    transfile = "$base/translations/pds4ExportBandBin.trn";
-    PvlToXmlTranslationManager xlator(*inputLabel, transfile.expanded());
+  void ProcessExportPds4::translateBandBinImage(Pvl &inputLabel) {
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp]: add documentation

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp [hunk 5]
```diff
@@ -291,35 +406,281 @@ namespace Isis {
...
     xlator.Auto(*m_domDoc);
+  }
 
-    // Add header info
-    addSchema("PDS4_SP_1100.sch", 
-              "PDS4_SP_1100.xsd",
-              "xmlns:sp", 
-              "http://pds.nasa.gov/pds4/sp/v1"); 
+
+  void ProcessExportPds4::translateBandBinSpectrumUniform(Pvl &inputLabel) {
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp]: add documentation

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp [hunk 6]
```diff
@@ -291,35 +406,281 @@ namespace Isis {
...
+          PvlToXmlTranslationManager::setElementValue(filterNumber, number[i]);
+          filter.appendChild(filterNumber);
+        }
+      }
+    }
+    
+  }
+
+
+  void ProcessExportPds4::translateBandBinSpectrumBinSet(Pvl &inputLabel) {
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.cpp]: add documentation

File: isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.h [hunk 7]
```diff
@@ -96,22 +107,32 @@ namespace Isis {
...
+      void setSchemaLocation(QString schema);
+      void setImageType(ImageType imageType);
 
       static void translateUnits(QDomDocument &label,
                                  QString transMapFile = "$base/translations/pds4ExportUnits.pvl");
 
-    protected:
       void addSchema(QString sch, QString xsd, QString xmlns, QString xmlnsURI) ;
+    protected:
+//      void addSchema(QString sch, QString xsd, QString xmlns, QString xmlnsURI) ;
```
Comment (krlberry) [inline isis/src/base/objs/ProcessExportPds4/ProcessExportPds4.h]: remove this line?

File: isis/src/control/objs/ControlNetVersioner/unitTest.cpp [hunk 8]
```diff
@@ -16,57 +16,115 @@ using namespace Isis;
```
Comment (krlberry) [inline isis/src/control/objs/ControlNetVersioner/unitTest.cpp:16]: I just want to make sure -- should these ControlNetVersioner unitTest changes be part of this PR? They all look like documentation / formatting changes, and if so, this seems okay to me. I just wanted to double-check.

File: isis/src/tgo/apps/tgocassisrdrgen/tsts/default/Makefile [hunk 9]
```diff
@@ -1,43 +0,0 @@
-APPNAME = tgocassisrdrgen
```
Comment (krlberry) [inline isis/src/tgo/apps/tgocassisrdrgen/tsts/default/Makefile:1]: Just want to double-check and make sure that this was deliberately deleted?

**Review by krlberry — APPROVED** [review]
:+1: Happy to merge this whenever, after the merge conflict is resolved. The documentation changes can be made after merge.

**Comment by krlberry** [comment]
Never mind, this was an easy merge.
