### PR TITLE
ALE Spice Reduction

### LINKED ISSUE #3928: CTX images are using linear position interpolation instead of hermite
**ISIS version(s) affected**: 4.1.0 (likely 4.0) and later

**Description**  

When spiceinit'd with ISIS 4.1.0, some CTX images are using linear position interpolation instead of cubic hermite splines. This is causing errors on the order of a few meters vertically. Currently we've seen this with J03_045994_1986_XN_18N282W and J03_046060_1986_XN_18N282W so far. It is likely occurring in more images.

**How to reproduce**  

Spiceinit the cube with ISIS3 and then spiceinit the cube with ISIS4. The InstrumentPosition CacheType will be HermiteSpline under ISIS3 and Linear under ISIS4.

**Possible Solution**  

This is likely caused by the cache being significantly smaller when ALE creates it compared to ISIS.
**Additional context**

### PR DESCRIPTION
**Pull request by acpaquette**
Uses ISIS methods to reduce the ephemeris data coming in from ALE.

## Description
Manual calls the reduction methods for m_instrumentPosition, m_instrumentRotation, m_sunPosition, and m_bodyRotation so that each object will be in the same state by the end of an ALE spiceinit as if they had been run through the old ISIS spiceinit routine. With state mainly referring to the p_source state of each object. 

There are some differences with the number of records, notably m_instrumentPosition and m_instrumentRotation.

## Related Issue
Fixes #3928 

## Motivation and Context
This was an attempt to apply the ISIS reduction methods to ALE ephemeris data so that the two are more in line with each other.

## How Has This Been Tested?
Usual ISIS tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/base/objs/SpicePosition/SpicePosition.h [hunk 1]
```diff
@@ -250,6 +250,11 @@ namespace Isis {
         return (p_cache.size() > 0);
       };
 
+      //! Is this position cached
+      int cacheSize() const {
```
Comment (jessemapel) [inline isis/src/base/objs/SpicePosition/SpicePosition.h:254]: Can you add a check in the unit test for these?

**Comment by jessemapel** [comment]
There's a few app tests failing:

```
The following tests FAILED:
	403 - ckwriter_app_test_lronac (Failed)
	404 - ckwriter_app_test_messenger (Failed)
	1301 - mdisedrinfo_app_test_kernelchk (Failed)
	1492 - socetlinescankeywords_app_test_noblobs (Failed)
Errors while running CTest
```

and a ton of gtests are failing with seg faults on this.

**Comment by jessemapel** [comment]
@acpaquette Can you test that this addresses #3928?

File: isis/src/base/objs/Spice/Spice.cpp [hunk 2]
```diff
@@ -374,13 +374,20 @@ namespace Isis {
...
-    
+
 
     // Check to see if we have nadir pointing that needs to be computed &
-    // See if we have table blobs to load 
+    // See if we have table blobs to load
     if (m_usingAle) {
-      m_sunPosition->LoadCache(isd["sun_position"]);
-      m_bodyRotation->LoadCache(isd["body_rotation"]);
+      m_sunPosition->LoadCache(isd["SunPosition"]);
```
Comment (jessemapel) [inline isis/src/base/objs/Spice/Spice.cpp]: These names changed back to the old names. It looks like that is breaking things.

File: isis/src/base/objs/SpicePosition/SpicePosition.h [hunk 3]
```diff
@@ -250,6 +250,11 @@ namespace Isis {
         return (p_cache.size() > 0);
       };
 
+      //! Is this position cached
```
Comment (krlberry) [inline isis/src/base/objs/SpicePosition/SpicePosition.h]: Update docstring -- this is size of cache, not "is position cached"

File: isis/src/base/objs/Spice/Spice.cpp [hunk 4]
```diff
@@ -374,13 +374,20 @@ namespace Isis {
...
+      if (m_sunPosition->cacheSize() > 3) {
+        m_sunPosition->Memcache2HermiteCache(0.01);
+      }
+      m_bodyRotation->LoadCache(isd["BodyRotation"]);
+      m_bodyRotation->MinimizeCache(SpiceRotation::DownsizeStatus::Yes);
```
Comment (krlberry) [inline isis/src/base/objs/Spice/Spice.cpp:387]: Did you end up verifying that `SpiceRotation::DownsizeStatus::No` isn't used anywhere? Because this would over-ride that, right?

Comment (acpaquette) [reply isis/src/base/objs/Spice/Spice.cpp:387]: I know that Done isn't being used anywhere if that's what you are talking about. I think No is used in a couple of places.

File: isis/src/base/objs/SpiceRotation/SpiceRotation.truth [hunk 5]
```diff
@@ -656,7 +657,7 @@ CJ(3) = -8.6595606e-17 2.220446e-16 -1
 
 
 Testing loading cache from ALE ISD with time dependent quaternions and AV ...
-Has AV? Yes
+Has AV? No
```
Comment (jessemapel) [inline isis/src/base/objs/SpiceRotation/SpiceRotation.truth]: Why did this change?

Comment (acpaquette) [reply isis/src/base/objs/SpiceRotation/SpiceRotation.truth]: No sure, I thought it was changing from No to Yes. I'll take another look

**Comment by jessemapel** [comment]
This looks good, but there are still 2 tests failing:

isis3_unit_test_SpiceRotation
ckwriter_app_test_messenger

**Review by jessemapel — APPROVED** [review]
Tested locally on Ubuntu and OSX while Jenkins is coming back online. Everything passed so this is good to go.
