### PR TITLE
Spice Server Associated Changes

### LINKED ISSUE #4044: ISIS Spice Server returning incomplete responses on 4.2.0
**ISIS version(s) affected**: 4.x.x 

**Description**  

When using spiceinit with web=yes, the spice server sometimes gives a partial response. 

**How to reproduce**  

Run spiceinit with web=yes, it doesn't seem to matter what cube you use. 

```bash
(isis4.2.0) krodriguez@smalls:~$ spiceinit from=I53972019RDR.QUB.cub web=yes
**ERROR** The server sent an unrecognized response [3c73706963655f646174613e0a20203c6170706c69636174696f6e5f6c6f673e0a34373732366637353730323033643230346236353732366536353663373330613230323034653631363936363436373236313664363534333666363436353230323032303230323032303230323032303230323032303230336432303264333533333330333333313061323032303463363536313730353336353633366636653634323032303230323032303230323032303230323032303230323032303230323033643230323436323631373336353266366236353732366536353663373332663663373336623266366536313639363633303330333133323265373436633733306132303230353436313732363736353734343137343734363937343735363436353533363836313730363532303230323032303230323032303364323032343632363137333635326636623635373236653635366337333266373036333662326637303633366233303330333033303339326537343730363330613230323035343631373236373635373435303666373336393734363936663665323032303230323032303230323032303230323032303230336432303238323436323631373336353266366236353732366536353663373332663733373036623266363436353334333333303265363237333730326330613230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323436323631373336353266366236353732366536353663373332663733373036623266366436313732333033393337326536323733373032393061323032303439366537333734373237353664363536653734353036663639366537343639366536373230323032303230323032303230323033643230323832343666363437393733373336353739326636623635373236653635366337333266363336623266366433303331356637333633356636353738373433333338326536323633326330613230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323436663634373937333733363537393266366236353732366536353663373332663636366232663664333033313566373633323339326537343636323930613230323034393665373337343732373536643635366537343230323032303230323032303230323032303230323032303230323032303230336432303465373536633663306132303230353337303631363336353633373236313636373434333663366636333662323032303230323032303230323032303230323032303364323032343666363437393733373336353739326636623635373236653635366337333266373336333663366232663466353234323331356635333433346334623533343334353534326533303330333233353339326537343733363330613230323034393665373337343732373536643635366537343530366637333639373436393666366532303230323032303230323032303230336432303234366636343739373337333635373932663662363537323665363536633733326637333730366232663664333033313566363537383734333333383265363237333730306132303230343936653733373437323735366436353665373434313634363436353665363437353664323032303230323032303230323032303364323032343666363437393733373336353739326636623635373236653635366337333266363936313662326637343638363536643639373334313634363436353665363437353664333033303333326537343639306132303230353336383631373036353464366636343635366332303230323032303230323032303230323032303230323032303230323032303364323032343632363137333635326636343635366437333266366436663663363134643631373237333530366336313665363537343631373237393532363136343639373537333330333033303335326536333735363230613230323034393665373337343732373536643635366537343530366637333639373436393666366535313735363136633639373437393230336432303532363536333666366537333734373237353633373436353634306132303230343936653733373437323735366436353665373435303666363936653734363936653637353137353631366336393734373932303364323035323635363336663665373337343732373536333734363536343061323032303433363136643635373236313536363537323733363936663665323032303230323032303230323032303230323032303230323033643230333230613230323035333666373537323633363532303230323032303230323032303230323032303230323032303230323032303230323032303230336432303639373336393733306134353665363435663437373236663735373030613435366536340a20203c2f6170706c69636174696f6e5f6c6f673e0a20203c6b65726e656c735f6c6162656c3e0a34663632366136353633373432303364323034653631363936363462363537393737366637323634373330613230323034323466343435393566343334663434343532303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303364323033343339333930613230323034323466343435393334333933393566353234313434343934393230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303364323032383333333333393336326533313339326332303333333333393336326533313339326332303333333333373336326533323239306132303230343234663434353935663436353234313464343535663433346634343435323032303230323032303230323032303230323032303230323032303230323032303230323032303230323033643230333133303330333133343061323032303433346334663433346235663435353435663264333533333566333133303337333633373331333133333335333232653330333233353566343334663464353035353534343534343230336432303632333133393339363536363631363433303337333836353632363133343331306132303230343934653533326433353333333033333331356635343532343134653533353832303230323032303230323032303230323032303230323032303230323032303230323032303230323033643230323833303265333032633230333032653330333532633230333032653330323930613230323034393465353332643335333333303333333135663534353234313465353335393230323032303230323032303230323032303230323032303230323032303230323032303230323032303364323032383330326533303263323033303265333032633230333032653330333532393061323032303439346535333264333533333330333333313566343935343532343134653533353332303230323032303230323032303230323032303230323032303230323032303230323032303230336432303238333032653330326332303332333032653330326332303330326533303239306132303230343934653533326433353333333033333331356634393534353234313465353334633230323032303230323032303230323032303230323032303230323032303230323032303230323033643230323833303265333032633230333032653330326332303332333032653330323930613435366536343566346636323661363536333734306130613437373236663735373032303364323034623635373236653635366337333061323032303465363136393636343637323631366436353433366636343635323032303230323032303230323032303230323032303230323033643230326433353333333033333331306132303230346336353631373035333635363336663665363432303230323032303230323032303230323032303230323032303230323032303364323032343632363137333635326636623635373236653635366337333266366337333662326636653631363936363330333033313332326537343663373330613230323035343631373236373635373434313734373436393734373536343635353336383631373036353230323032303230323032303230336432303234363236313733363532663662363537323665363536633733326637303633366232663730363336623330333033303330333932653734373036333061323032303534363137323637363537343530366637333639373436393666366532303230323032303230323032303230323032303230323033643230323835343631363236633635326332303234363236313733363532663662363537323665363536633733326637333730366232663634363533343333333032653632373337303263306132303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303234363236313733363532663662363537323665363536633733326637333730366232663664363137323330333933373265363237333730323930613230323034393665373337343732373536643635366537343530366636393665373436393665363732303230323032303230323032303230336432303238353436313632366336353263323032343666363437393733373336353739326636623635373236653635366337333266363336623266366433303331356637333633356636353738373433333338326536323633326330613230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323436663634373937333733363537393266366236353732366536353663373332663636366232663664333033313566373633323339326537343636323930613230323034393665373337343732373536643635366537343230323032303230323032303230323032303230323032303230323032303230336432303465373536633663306132303230353337303631363336353633373236313636373434333663366636333662323032303230323032303230323032303230323032303364323032343666363437393733373336353739326636623635373236653635366337333266373336333663366232663466353234323331356635333433346334623533343334353534326533303330333233353339326537343733363330613230323034393665373337343732373536643635366537].
```

Note, the large block is the response from the server which is an XML string in HEX form . 

Converting it back to ASCII: 

```xml
<spice_data>
  <application_log>
47726f7570203d204b65726e656c730a20204e6169664672616d65436f6465202020202020202020202020203d202d35333033310a20204c6561705365636f6e64202020202020202020202020202020203d2024626173652f6b65726e656c732f6c736b2f6e616966303031322e746c730a202054617267657441747469747564655368617065202020202020203d2024626173652f6b65726e656c732f70636b2f70636b30303030392e7470630a2020546172676574506f736974696f6e2020202020202020202020203d202824626173652f6b65726e656c732f73706b2f64653433302e6273702c0a2020202020202020202020202020202020202020202020202020202020202024626173652f6b65726e656c732f73706b2f6d61723039372e627370290a2020496e737472756d656e74506f696e74696e6720202020202020203d2028246f6479737365792f6b65726e656c732f636b2f6d30315f73635f65787433382e62632c0a20202020202020202020202020202020202020202020202020202020202020246f6479737365792f6b65726e656c732f666b2f6d30315f7632392e7466290a2020496e737472756d656e74202020202020202020202020202020203d204e756c6c0a202053706163656372616674436c6f636b20202020202020202020203d20246f6479737365792f6b65726e656c732f73636c6b2f4f5242315f53434c4b534345542e30303235392e7473630a2020496e737472756d656e74506f736974696f6e20202020202020203d20246f6479737365792f6b65726e656c732f73706b2f6d30315f65787433382e6273700a2020496e737472756d656e74416464656e64756d20202020202020203d20246f6479737365792f6b65726e656c732f69616b2f7468656d6973416464656e64756d3030332e74690a202053686170654d6f64656c202020202020202020202020202020203d2024626173652f64656d732f6d6f6c614d617273506c616e6574617279526164697573303030352e6375620a2020496e737472756d656e74506f736974696f6e5175616c697479203d205265636f6e73747275637465640a2020496e737472756d656e74506f696e74696e675175616c697479203d205265636f6e73747275637465640a202043616d65726156657273696f6e202020202020202020202020203d20320a2020536f7572636520202020202020202020202020202020202020203d20697369730a456e645f47726f75700a456e64
  </application_log>
  <kernels_label>
4f626a656374203d204e6169664b6579776f7264730a2020424f44595f434f4445202020202020202020202020202020202020202020202020202020203d203439390a2020424f44593439395f52414449492020202020202020202020202020202020202020202020203d2028333339362e31392c20333339362e31392c20333337362e32290a2020424f44595f4652414d455f434f4445202020202020202020202020202020202020202020203d2031303031340a2020434c4f434b5f45545f2d35335f313037363731313335322e3032355f434f4d5055544544203d20623139396566616430373865626134310a2020494e532d35333033315f5452414e53582020202020202020202020202020202020202020203d2028302e302c20302e30352c20302e30290a2020494e532d35333033315f5452414e53592020202020202020202020202020202020202020203d2028302e302c20302e302c20302e3035290a2020494e532d35333033315f495452414e535320202020202020202020202020202020202020203d2028302e302c2032302e302c20302e30290a2020494e532d35333033315f495452414e534c20202020202020202020202020202020202020203d2028302e302c20302e302c2032302e30290a456e645f4f626a6563740a0a47726f7570203d204b65726e656c730a20204e6169664672616d65436f6465202020202020202020202020203d202d35333033310a20204c6561705365636f6e64202020202020202020202020202020203d2024626173652f6b65726e656c732f6c736b2f6e616966303031322e746c730a202054617267657441747469747564655368617065202020202020203d2024626173652f6b65726e656c732f70636b2f70636b30303030392e7470630a2020546172676574506f736974696f6e2020202020202020202020203d20285461626c652c2024626173652f6b65726e656c732f73706b2f64653433302e6273702c0a2020202020202020202020202020202020202020202020202020202020202024626173652f6b65726e656c732f73706b2f6d61723039372e627370290a2020496e737472756d656e74506f696e74696e6720202020202020203d20285461626c652c20246f6479737365792f6b65726e656c732f636b2f6d30315f73635f65787433382e62632c0a20202020202020202020202020202020202020202020202020202020202020246f6479737365792f6b65726e656c732f666b2f6d30315f7632392e7466290a2020496e737472756d656e74202020202020202020202020202020203d204e756c6c0a202053706163656372616674436c6f636b20202020202020202020203d20246f6479737365792f6b65726e656c732f73636c6b2f4f5242315f53434c4b534345542e30303235392e7473630a2020496e737472756d656e7
```

The response is expected to be formatted more like: 

```xml
<spice_data>
  <application_log>
   . . . 
  </application_log>
  
   <kernels_label>
   . . . 
  </kernels_label>
  <tables>
    <instrument_pointing>
    . . . 
    </instrument_pointing>

    <instrument_position>
    . . . 
    </instrument_position>

    <body_rotation>
    . . . 
    </body_rotation>

    <sun_position>
    . . . 
    </sun_position>

  </tables>
</spice_data>
``` 

Clearly, not all the data is getting across the wire, therefore triggering the unknown response error (which is a catchall parsing error). 

This at least occurs when using ISIS 4.2.0 on the spice server. 

**Possible Solution**  

Currently, my hunch is this is a server issue as it started when the spice server's ISIS install switched to 4.2.0. Testing the Perl script might give some hints as to what is happening. 

**Additional context**  

The spice server is on the internal machine `isis-spice-d` and the Perl scripts are at `isis-spice-d:/var/www/cgi-bin/isis/spiceinit.cgi`

ISIS install is at `/work1/work2/isis3/isis`

`/work1/work2/isis3/isis4.2.0` contains a full ISIS4.2.0 install.

### PR DESCRIPTION
**Pull request by acpaquette**
Updates a few things regarding debugging the `spiceserver` and fixes a small bug when spiceiniting from the web.

## Description
Moves a commented out section of code from the `spiceserver` app to `SpiceClient` and can be accessed when run with `spiceinit from=... web=true`. This is likely where the code should have been and makes debugging slightly less painful.

This PR also addresses a small bug when running with `web=true`, where the `NaifKeywords` PvlObject would not be replaced when run on a cube that has already been spiceinit'd.

## Related Issue
Closes #4044 

## Motivation and Context
Updates the `spiceserver` to something newer than ISIS 3.5.0 and remains backwards compatible to ISIS 3.7.0 (Checked with MRO CTX image)

## How Has This Been Tested?
This PR does not contain the scope of the ticket as the spiceserver hosted under Astro is not properly versioned. I manually tested all minor versions (ISIS X.X.0) of ISIS from ISIS 3.7.0 - 6.0.0-RC1 with an MRO CTX image, all versions tested worked with the new ISIS 5.0.2 server (The newest stable release)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/base/apps/spiceinit/spiceinit.cpp [hunk 1]
```diff
@@ -684,7 +684,12 @@ namespace Isis {
       log->addGroup(kernelsGroup);
     }
 
-    icube->label()->addObject(naifKeywords);
+    Pvl *icubeLabel = icube->label();
+
+    if (icubeLabel->hasObject(naifKeywords.name())) {
+      icubeLabel->deleteObject(naifKeywords.name());
+    }
+    icubeLabel->addObject(naifKeywords);
```
Comment (Kelvinrr) [inline isis/src/base/apps/spiceinit/spiceinit.cpp:692]: Wait so is this also the root of the response being incomplete? Or is this more like a separate bug you just happen to find and fix?

Comment (acpaquette) [reply isis/src/base/apps/spiceinit/spiceinit.cpp:692]: No, this was a separate issue that I figured I could just fix. Honestly I still don't know exactly what was causing the error on the ISIS 4.2.0 server but after updating to 5.0.2 the problem fixed itself.

**Review by Kelvinrr — APPROVED** [review]

File: isis/src/base/apps/spiceinit/spiceinit.cpp (hunk 1 above)
Comment (Kelvinrr) [reply isis/src/base/apps/spiceinit/spiceinit.cpp:692]: we take those
