### PR TITLE
Fixed Bug in EquatorialCylindricalShape Fixes #5242

### LINKED ISSUE #5242: downloadIsisData not working
I am new to using linux and I am having some trouble downloading Isis data. When I attempt to use $ downloadIsisData all $ISISDATA it returns "downloadIsisData: command not found...". I am running CentOS Linux. Any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by cneubauerUSGS**
Removed the virtual method call of intersectEllipsoid and instead added a virtual call for setTargetRadii that is called inside of intersectEllipsoid to avoid code redundancy as that was the only difference in the two functions.

### CODE REVIEW

File: isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.h [hunk 1]
```diff
@@ -47,6 +47,11 @@ namespace Isis {
    *                           intersection in intersectSurface() method to prevent early return
    *                           and attempt the iterative method even when the ellipsoid is not
    *                           intersected. Fixes #1438
+   *   @history 2018-02-05 Cole Neubauer - Added the setTargetRadii virtual method so that the 
+   *                           intersectEllipsoid method can use a the MaximumRadius found in the
```
Comment (jcwbacker) [inline isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.h]: typo
"intersectEllipsoid method can use a the MaximumRadius"

File: isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.h [hunk 2]
```diff
@@ -60,11 +65,14 @@ namespace Isis {
       bool intersectSurface(std::vector<double> observerPos,
                             std::vector<double> lookDirection);
 
+    protected:
+      virtual void setTargetRadii(SpiceDouble &a, SpiceDouble &b, SpiceDouble &c);
```
Comment (jcwbacker) [inline isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.h]: We want to avoid passing by reference for this type of method. You should return a list of values or have a member variable that is set inside this method.

File: isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.cpp [hunk 3]
```diff
@@ -407,9 +410,24 @@ namespace Isis {
...
+  /**
+   * Override of virtual function for intersectEllipsoid
+   *
+   * param &a SpiceDouble reference to be set
+   *
+   * param &b SpiceDouble reference to be set
+   *
+   * param &c SpiceDouble reference to be set
+   */
+  void EquatorialCylindricalShape::setTargetRadii(SpiceDouble &a, SpiceDouble &b, SpiceDouble &c) {
```
Comment (jcwbacker) [inline isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.cpp]: see header file comment

File: isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.cpp [hunk 4]
```diff
@@ -407,9 +410,24 @@ namespace Isis {
...
   }
-  // Do nothing since the DEM intersection was already successful
-}
 
+
+  /**
+   * Override of virtual function for intersectEllipsoid
+   *
+   * param &a SpiceDouble reference to be set
+   *
```
Comment (jcwbacker) [inline isis/src/base/objs/EquatorialCylindricalShape/EquatorialCylindricalShape.cpp]: remove lines between params and give more descriptive documentation. (But this is a comment just for future reference, since I think you should remove these parameters - see other comments)

File: isis/src/base/objs/ShapeModel/ShapeModel.h [hunk 5]
```diff
@@ -74,6 +77,11 @@ namespace Isis {
    *                            setSurfacePoint() & clearSurfacePoint() virtual
    *                            to give some hope of a consistent internal state
    *                            in derived models.
+   *   @history 2018-02-05 Cole Neubauer - added virtual method setTargetRadii to be 
+   *                            called from intersectEllipsoid. This is to avoid
```
Comment (jcwbacker) [inline isis/src/base/objs/ShapeModel/ShapeModel.h]: https://isis.astrogeology.usgs.gov/documents/CodingStandards/CodingStandards.html#documentationFormatting
"When wrapping a Doxygen history entry, the subsequent lines should begin 4 spaces after the first name of the first programmer submitting the change."

If prior history entries are improperly indented, please fix them too.

File: isis/src/base/objs/ShapeModel/ShapeModel.h [hunk 6]
```diff
@@ -164,20 +172,28 @@ namespace Isis {
                                  const std::vector<double> lookDirection);
 
     protected:
+      // Virtual function to be called in intersectEllipsoid to avoid redundant code
+      virtual void setTargetRadii(SpiceDouble &a, SpiceDouble &b, SpiceDouble &c);
```
Comment (jcwbacker) [inline isis/src/base/objs/ShapeModel/ShapeModel.h]: virtual void setTargetRadii(); // setting member variable
or
virtual QVector<SpiceDouble> setTargetRadii(); // returning list

File: isis/src/base/objs/ShapeModel/ShapeModel.h [hunk 7]
```diff
@@ -164,20 +172,28 @@ namespace Isis {
...
       // Set shape name
       void setName(QString name);
 
       void calculateEllipsoidalSurfaceNormal();
-      bool hasEllipsoidIntersection();
 
       // Intersect ellipse
-      bool intersectEllipsoid(const std::vector<double> observerPosRelativeToTarget,
-                              const std::vector<double> &observerLookVectorToTarget);
+      bool intersectEllipsoid(
```
Comment (jcwbacker) [inline isis/src/base/objs/ShapeModel/ShapeModel.h]: keep first input param on same line unless it goes over 100 char

File: isis/src/base/objs/ShapeModel/ShapeModel.cpp [hunk 8]
```diff
@@ -198,6 +198,23 @@ namespace Isis {
     return acos(angle) * RAD2DEG;
   }
 
+  /**
+   * Sets the parameters to the Target radii
+   *
+   * param &a SpiceDouble reference to be set
+   *
+   * param &b SpiceDouble reference to be set
+   *
```
Comment (jcwbacker) [inline isis/src/base/objs/ShapeModel/ShapeModel.cpp]: see header comment

File: isis/src/base/objs/ShapeModel/ShapeModel.h [hunk 9]
```diff
@@ -164,20 +172,28 @@ namespace Isis {
...
+      virtual void setTargetRadii(SpiceDouble &a, SpiceDouble &b, SpiceDouble &c);
+
 
       // Set the normal (surface or local) of the current intersection point
       void setNormal(const std::vector<double>);
       void setNormal(const double a, const double b, const double c);
 
+      // accessor and setter for m_hasEllipsoidIntersection
+      bool hasEllipsoidIntersection();
+      // void setHasEllipsoidIntersection(bool status);
```
Comment (jcwbacker) [inline isis/src/base/objs/ShapeModel/ShapeModel.h]: if it turns out we don't need this method, then you can remove it.

**Review by jcwbacker — CHANGES_REQUESTED** [review]
Looks good. Just a few more recommendations. Also, can you change the name of the PR to user-friendly description of your changes (similar to svn commit message).

**Review by jcwbacker — APPROVED** [review]
