### PR TITLE
Changed FileName to use US English for date conversions

### LINKED ISSUE #3340: spiceinit for Cassini can't find newest PCK
**ISIS version(s) affected: All at time of issue creation 3.7.1

**Description**  
I’ve been running into some trouble with the Spiceinit module in ISIS 3.6.2. I’m trying to process  data from the Cassini mission. I’m getting the following error:
“No existing files found with a date version matching [cpck{ddMMMyyyy}.tpc] in[.../isis3/data/cassini/kernels/pck]”
when running: 
`spiceinit from=v1637464787_1_ir
`

See discussion at: https://astrodiscuss.usgs.gov/t/spiceinit-error/171

**How to reproduce**  
With ISIS 3.7.1 or earlier and the bash shell
```
export LC_TIME=nl_NL.UTF-8
spiceinit from=v1637464787_1_ir FAILS

export LC_TIME=“en_US.UTF-8”
spiceinit from=v1637464787_1_ir SUCCEEDS
```

**Possible Solution**  
Find out why the setting of LC_ALL in the Application class constructor is not being honored.

**Additional context**  
spiceinit / kerneldb / filename / highestversion is searching for a kernel file that uses a date as the version number in: .../data/cassini/kernels/pck/cpckDDMMMYYYY.tpc
That search comes back empty when the LC_TIME locale is set to nl_NL.

### PR DESCRIPTION
**Pull request by jessemapel**
If the user is set to a non-English language, then finding the latest version of files that use short names of months fails. Now FileName always uses US English for string to date conversions.

## Description

For example, if a file uses something like 15Dec2017 and the users language is set to Spanish, then FileName cannot properly convert Dec to the 12th month because it is looking for the Spanish word for December. There is existing code in ISIS that sets these at the system level, but the QT locale utilities are not properly updating on linux (oddly this doesn't seem to be a problem on Mac). So, I added code to set the default in QT to US English and changed calls to use the default instead of the system locale.

## Related Issue

Fixes #3340 

## Motivation and Context

Users with non-English language settings had odd failures during spiceinit. See https://astrodiscuss.usgs.gov/t/spiceinit-error/171 for more info.

## How Has This Been Tested?

Tested on Mac and Linux with Cassini VIMS data because it uses kernels ranked by the date they were created.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/base/objs/FileName/FileName.cpp [hunk 1]
```diff
@@ -622,8 +623,7 @@ namespace Isis {
                     foundFile.mid(truncateRange.second + 1);
 
       }
-
-      QDate fileDate = QDate::fromString(foundFile, fileQDatePattern);
+      QDate fileDate = QLocale().toDate(foundFile, fileQDatePattern);
```
Comment (scsides) [inline isis/src/base/objs/FileName/FileName.cpp]: This member was designed to work with US English locale ONLY. Would it be better to force this call to use US English, and not rely on the Application to set it correctly?

**Review by scsides — CHANGES_REQUESTED** [review]
This should work. Comments on my request appreciated

**Review by scsides — APPROVED** [review]

File: isis/tests/FileListTests.cpp [hunk 2]
```diff
@@ -11,12 +11,12 @@ TEST(FileList, NonExistantFileConstructor)
...
   catch(Isis::IException &e)
   {
-    EXPECT_TRUE(e.toString().toLatin1().contains("Unable to open [FakeFile]."))
+    EXPECT_TRUE(e.toString().toLatin1().contains("Unable to open [FakeFile]"))
       << e.toString().toStdString();
   }
   catch(...)
   {
-    FAIL() << "Expected an IException\"Unable to open [FakeFile].\"";
+    FAIL() << "Expected an IException\"Unable to open [FakeFile]\"";
```
Comment (jessemapel) [inline isis/tests/FileListTests.cpp:19]: Technically this is outside of the scope of the PR, but it's such a simple change I think it will be okay.
