### PR TITLE
Fixed bug for Rosetta OSIRIS ingestion app, rososiris2isis, that did not recognize the Fe2O3 filter. Fixes #5369.

### LINKED ISSUE #5369: Documentation is out of date
**Description**

The latest documentation version is 7.0.0, but the current LTS is 8.0.1 or 8.0.2. The docs are a full major version behind the current release. 

**Suggested Edit**

Please update the docs with the new version.

Thanks!

### PR DESCRIPTION
**Pull request by jcwbacker**
Filter name comparisons were moved out of the code to a translation file in order to fix such errors without the need to recompile.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -27,10 +27,11 @@ object_script.*.Debug
 *_plugin_import.cpp
 *.moc
 ui_*.h
-*.html
+*html
```
Comment (krlberry) [inline .gitignore:30]: Why `*html` instead of `*.html`? (What kind of additional files is this filtering out that the old one didn't catch?)

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp [hunk 2]
```diff
@@ -365,97 +372,149 @@ namespace Isis {
...
-    if(!p_trnsTbl.hasGroup(nName)) {
-      QString msg = "Unable to find translation group [" +
-                   nName + "] in file [" + p_trnsTbl.fileName() + "]";
-      throw IException(IException::Programmer, msg, _FILEINFO_);
-    }
+    const PvlGroup &translationGroup = findTranslationGroup(translationGroupName);
 
-    PvlGroup tgrp = p_trnsTbl.findGroup(nName);
-    if(tgrp.hasKeyword("InputDefault")) return tgrp["InputDefault"];
+    if (translationGroup.hasKeyword("InputDefault")) return translationGroup["InputDefault"];
```
Comment (krlberry) [inline isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:386]: Should this use `hasInputDefault()` ?

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp [hunk 3]
```diff
@@ -340,22 +352,17 @@ namespace Isis {
    * Returns the input keyword name from the translation table corresponding to
    * the output name argument.
    *
-   * @param nName The output name to be used to search the translation table.
+   * @param translationGroupName The output name to be used to search the translation table.
    *
    * @return QString The input keyword name
    *
-   * @throws iException::Programmer
+   * @throws IException::Programmer
```
Comment (krlberry) [inline isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp]: Do we document the exception here with `@throws`, if the exception is actually thrown from `findTranslationGroup`? (A function called by this function)

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp [hunk 4]
```diff
@@ -340,22 +352,17 @@ namespace Isis {
...
-    if(!p_trnsTbl.hasGroup(nName)) {
-      QString msg = "Unable to find translation group [" +
-                   nName + "] in file [" + p_trnsTbl.fileName() + "]";
-      throw IException(IException::Programmer, msg, _FILEINFO_);
-    }
+    const PvlGroup &translationGroup = findTranslationGroup(translationGroupName);
 
-    PvlGroup tgrp = p_trnsTbl.findGroup(nName);
-    if(tgrp.hasKeyword("InputKey")) return tgrp["InputKey"];
+    if (translationGroup.hasKeyword("InputKey")) return translationGroup["InputKey"];
```
Comment (krlberry) [inline isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:368]: Should this use `hasInputKey()` ?

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp [hunk 5]
```diff
@@ -365,97 +372,149 @@ namespace Isis {
    * Returns the input default value from the translation table corresponding
    * to the output name argument.
    *
-   * @param nName The output name to be used to search the translation table.
+   * @param translationGroupName The output name to be used to search the translation table.
    *
    * @return QString The input default value
    *
-   * @throws iException::Programmer
+   * @throws IException::Programmer
```
Comment (krlberry) [inline isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp]: Do we document the exception here with `@throws`, if the exception is actually thrown from `findTranslationGroup`?

File: isis/src/rosetta/apps/rososiris2isis/PvlTranslationTable.cpp [hunk 6]
```diff
@@ -0,0 +1 @@
+/scratch/ISIS3/isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp
```
Comment (krlberry) [inline isis/src/rosetta/apps/rososiris2isis/PvlTranslationTable.cpp]: I'm not sure what this is, but I think it should be removed from the PR. Is this a symlink to `/scratch/ISIS3/isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp` from your `isis/src/rosetta/apps/rososiris2isis` area? I am not sure how this shows up in a PR.

File: isis/src/rosetta/apps/rososiris2isis/PvlTranslationTable.h [hunk 7]
```diff
@@ -0,0 +1 @@
+/scratch/ISIS3/isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.h
```
Comment (krlberry) [inline isis/src/rosetta/apps/rososiris2isis/PvlTranslationTable.h]: I'm not sure what this is, but I think it should be removed from the PR. Is this a symlink to `/scratch/ISIS3/isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.h` from your `isis/src/rosetta/apps/rososiris2isis` area? I am not sure how this shows up in a PR.

File: isis/src/rosetta/apps/rososiris2isis/osirisFilters.trn [hunk 8]
```diff
@@ -0,0 +1,148 @@
+#
```
Comment (krlberry) [inline isis/src/rosetta/apps/rososiris2isis/osirisFilters.trn]: Does this translation file belong at this location, or in `$ISIS3DATA/rosetta/translations` ? 

The actual file looks good! :+1:

File: isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp [hunk 9]
```diff
@@ -80,9 +80,10 @@ void translateCoreInfo(FileName &inputLabel, ProcessImport &importer) {
   // Get the directory where the Tgo translation tables are
   PvlGroup &dataDir = Preference::Preferences().findGroup("DataDirectory");
   QString missionDir = (QString) dataDir["Tgo"];
-  FileName transFile(missionDir + "/translations/tgoCassis.trn");
 
   // Get the translation manager ready
+  missionDir = ".";
```
Comment (krlberry) [inline isis/src/tgo/apps/tgocassis2isis/tgocassis2isis.cpp]: This looks like a temporarily-set missionDir that should be removed.

**Review by krlberry — CHANGES_REQUESTED** [review]
Looks good! In addition to fixing the `ososiris2isis` bug, all the changes to `XmlToPvlTranslationManager` make it much easier to read and understand what's going on! I caught a couple of very small things and had a few questions.

**Comment by krlberry** [comment]
I reviewed this a little early -- @jcwbacker I know you mentioned you were going to change a couple of small things.

File: .gitignore (hunk 1 above)
Comment (jcwbacker) [reply .gitignore:30]: because there are directories made by squish that are scopecoverage_html and I would like to ignore them too

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp (hunk 3 above)
Comment (jcwbacker) [reply isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp]: Nope. We shouldn't document it if this method doesn't throw it. Good catch.

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp (hunk 4 above)
Comment (jcwbacker) [reply isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:368]: i didn't find a method with this name

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp (hunk 2 above)
Comment (jcwbacker) [reply isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:386]: maybe not.  hasInputDefault(transGrpName) uses the group name to find the group first before determining whether the group has this keyword. 
in the translation method we have already searched and found the group and plan to use it elsewhere. 
I'm not sure why the hasInputDefault() method exists. It appears to only be used in XmlToPvlTranslationManager. And appears to be an inefficient design, but this is older code and out of the scope of this bug fix.

File: .gitignore (hunk 1 above)
Comment (krlberry) [reply .gitignore:30]: :+1: Thank you!

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp (hunk 2 above)
Comment (krlberry) [reply isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:386]: :+1: Thanks for explaining.

File: isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp (hunk 4 above)
Comment (krlberry) [reply isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp:368]: Oops, thought this was the same this as above, sorry (hasInputDefault) ! Nevermind.

**Review by krlberry — APPROVED** [review]
