### PR TITLE
IPCE changes - Fixes #5495, #5504, #5518.

### LINKED ISSUE #5495: Unable to add SPICE data to Galileo cube files
**ISIS version(s) affected**: x.y.z

**Description**  
Hello! We're facing issues with adding SPICE data to our Galileo cube files using the spiceinit function. I have pasted the error message below. Would really appreciate any help!

**How to reproduce**  
Last login: Sun May 5 22:53:24 on ttys000
(base) benson@dhcp-vl2041-18708 ~ % conda activate isis
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit
(isis) benson@dhcp-vl2041-18708 ~ % qimage
zsh: command not found: qimage
(isis) benson@dhcp-vl2041-18708 ~ % ls *.cub
7401r.cub 7452r.cub 8700r.cub 8726r.cub
(isis) benson@dhcp-vl2041-18708 ~ % qview 8700r.cub
^C
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r.cub attach=yes
ERROR No existing files found with a numerical version matching [kernels.????.db] in [/Applications/anaconda3/envs/isis/data/base/kernels/lsk].
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r.cub web=yes
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % ls *.cub
7401r.cub 7452r.cub 8700r.cub 8726r.cub
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8726r.cub web=yes
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % gllssi2isis from=8700r.lbl to=8700r_v2.cub
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r_v2.cub web=true
ERROR The server sent an unrecognized response.
(isis) benson@dhcp-vl2041-18708 ~ % spiceinit from=8700r_v2.cub attach=true
ERROR No existing files found with a numerical version matching [kernels.????.db] in [/Applications/anaconda3/envs/isis/data/base/kernels/lsk].
(isis) benson@dhcp-vl2041-18708 ~ %

### PR DESCRIPTION
**Pull request by TracieSucharski**
These changes only affect the ipce application:
Fixes #5495, fix seg fault when saving project with a shape open in the footprint view.
Fixes #5504, improve functionality changing ground, radius source in the control point editor view.
Fixes #5518, update the control net name on the footprint view when the active control net is changed.

### CODE REVIEW

File: isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp [hunk 1]
```diff
@@ -769,6 +756,20 @@ namespace Isis {
   }
 
 
+  void ControlMeasureEditWidget::setLeftPosition(double sample, double line) {
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp:766]: should there be a descriptive header for the setLeftPosition and setRightPosition methods?

File: isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp [hunk 2]
```diff
@@ -1670,16 +1708,6 @@ namespace Isis {
...
-
-
-
-
-//  TODO IPCE   2016-06-13  ALL CODE BELOW HERE IS TEMPORARY PROTOTYPE CODE  NEEDS MUCH CLEANUP, LEAKY MEMORY, ETC
-
-
-
-
   void ControlMeasureEditWidget::setPoint(ControlPoint *editPoint, SerialNumberList *snList) {
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp:1732]: method header?

File: isis/src/qisis/objs/ControlNetTool/ControlNetTool.cpp [hunk 3]
```diff
@@ -284,10 +288,23 @@ namespace Isis {
     // TODO: Should we add the SN to the viewPort
     QString serialNumber = SerialNumber::Compose(*vp->cube(), true);
 
-//    if (serialNumber == m_groundSN) {
-//      drawGroundMeasures(vp, painter);
-//      return;
-//    }
+    // Get list of shapes in the ipce project and see if the serial number for viewport passed in
+    // matches any of the project shapes.  If there's a match, draw any ground measures.
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlNetTool/ControlNetTool.cpp]: are you drawing ground "measures" or ground points?

File: isis/src/qisis/objs/ControlNetTool/ControlNetTool.h [hunk 4]
```diff
@@ -58,6 +58,8 @@ namespace Isis {
    *                           loaded.
    *   @history 2018-04-13 Tracie Sucharski - In mouseButtonRelease method return if a control net
    *                           has not been set.
+   *   @history 2018-09-21 Tracie Sucharski - Draw Fixed and Constrained points on ground cubes.
+   *                           Refereces #5504.
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlNetTool/ControlNetTool.h]: spelling (I know it's picky, but since you're here)

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp [hunk 5]
```diff
@@ -562,6 +559,72 @@ namespace Isis {
   }
 
 
+  /**
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:562]: having some trouble understanding this header

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp [hunk 6]
```diff
@@ -638,6 +701,38 @@ namespace Isis {
...
+   *
+   * @author 2013-12-06 Tracie Sucharski
+   *
+   * @internal
+   *   @history 2013-12-06 Tracie Sucharski - Original version.
+   *   @history 2015-05-19 Ian Humphrey and Makayla Shepherd - moved duplicated code to
+   *                           findPointLocation() and createTemporaryGroundMeasure().
+   *
+   */
+  void ControlPointEditWidget::loadGroundMeasure() {
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:715]: is this another "measure" vs ground point thing?

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp [hunk 7]
```diff
@@ -695,114 +774,376 @@ namespace Isis {
...
+                  QString::number(refRadii[2].meters());
 
-      groundFile = newFile.absoluteFilePath();
-      m_controlNet->GetPoint(i)->SetAprioriSurfacePointSourceFile(groundFile.expanded());
+      m_radiusFilename = "";
     }
   }
 
 
+  void ControlPointEditWidget::initDem (QString demFile) {
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:1011]: header?

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp [hunk 8]
```diff
@@ -885,122 +1225,148 @@ namespace Isis {
...
-    //  Set ignore box correctly
-    m_ignorePoint->setChecked(m_editPoint->IsIgnored());
 
-    // Clear combo boxes
-    m_leftCombo->clear();
-    m_rightCombo->clear();
-    m_pointFiles.clear();
-
-    //  If fixed, add ground source file to combos, create a measure for
+    //  If constrained or fixed point, create a measure for
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp]: again, measure?

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp [hunk 9]
```diff
@@ -1059,7 +1429,7 @@ namespace Isis {
 
   void ControlPointEditWidget::createControlPoint(double latitude, double longitude, Cube *cube,
```
Comment (kledmundson) [inline isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:1447]: header?

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp (hunk 6 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:715]: This is not, it is a ControlMeasure that is within a Fixed or Constrained ControlPoint.

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp (hunk 5 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:562]: I changed to:

  /**
   * Fill m_projectShapeNames with ALL shapes currently in project. The first 
   * m_numberProjectShapesWithPoint actually contain the location of m_editPoint.
   *
Does that help?

File: isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp (hunk 1 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp:766]: Added.

File: isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp (hunk 2 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp:1732]: Added documentation.

File: isis/src/qisis/objs/ControlNetTool/ControlNetTool.cpp (hunk 3 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlNetTool/ControlNetTool.cpp]: Changed to ground points.

File: isis/src/qisis/objs/ControlNetTool/ControlNetTool.h (hunk 4 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlNetTool/ControlNetTool.h]: Corrected spelling of Reference.

File: isis/src/qisis/objs/NewControlPointDialog/NewControlPointDialog.h [hunk 10]
```diff
@@ -43,6 +43,8 @@ namespace Isis {
    *                          check text instead of int values. Add tool tip explaining why point
    *                          type cannot be changed.  Set tool tip on Ok button explaining why it
    *                          is not enabled. Fixes #5087.
+   *   @history 2018-10-05 Tracie Sucharski - Add radius source combo for choosing the radius
```
Comment (kledmundson) [inline isis/src/qisis/objs/NewControlPointDialog/NewControlPointDialog.h]: should you mention the method name here?

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp (hunk 7 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:1011]: Added documentation.

File: isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp (hunk 9 above)
Comment (TracieSucharski) [reply isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp:1447]: Added documentation.

**Review by kledmundson — APPROVED** [review]
