### PR TITLE
Address UniversalGroundMap issue

### LINKED ISSUE #5896: qview Find tool still wrongly prioritizes camera model over map projection
**ISIS version(s) affected**: 8.3.0 and earlier

**Description**  
I believe this is very closely related to #5508, but a slightly different expression of the same underlying issue.  If you have a map-projected file with SPICE data covering only part of the image (I didn't realize this was even possible, but apparently that's what you get from map-projecting just the even or odd framelets of an LROC WAC image), then the Find tool does not correctly align linked images when you click in an area that is within the map projection bounds but does not have SPICE data.  Alignment works correctly in places that do have SPICE data, including not having the scaling issue from #5508.

**How to reproduce**  

```
wget https://pds.lroc.im-ldi.com/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0063B/DATA/ESM5/2025129/WAC/M1501447954CE.IMG
lrowac2isis from=M1501447954CE.IMG to=M1501447954C.cub
spiceinit from=M1501447954C.vis.even.cub
spiceinit from=M1501447954C.vis.odd.cub
cam2map from=M1501447954C.vis.even.cub to=M1501447954C.vis.even.map.cub
cam2map from=M1501447954C.vis.odd.cub to=M1501447954C.vis.odd.map.cub

echo "M1501447954C.vis.even.map.cub
M1501447954C.vis.odd.map.cub" > tmp.lis

automos from=tmp.lis mos=M1501447954C.vis.nospice.cub

/bin/mv M1501447954C.vis.odd.map.cub M1501447954C.vis.halfspice.cub
handmos from=M1501447954C.vis.even.map.cub mos=M1501447954C.vis.halfspice.cub

qview M1501447954C.vis.*spice.cub
```

Link the two images, zoom 1:1 or closer, and open the Tracking table and turn on the incidence column.  Using the Find tool, click in various places around either image.  Where the "halfspice" image has SPICE data (the incidence column has data, e.g. sample 900 line 5090), the two images will act properly linked.  Where it does not (e.g. sample 900 line 5100), clicking will not align the images.

### PR DESCRIPTION
**Pull request by acpaquette**
## Description
Fix UniversalGroundMap to consistently use map projections across qapps/tools

## Related Issue
Fixes #5896 

## How Has This Been Validated?
Validated qapps locally and ISIS test suite

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

File: isis/src/base/objs/UniversalGroundMap/UniversalGroundMap.h [hunk 1]
```diff
@@ -139,8 +139,12 @@ namespace Isis {
 
 
     private:
+      void setProjectionEngine(Cube *cube,  CameraPriority priority, bool owned);
+      void setProjection(Cube *cube, bool owned);
+      void setCamera(Cube *cube, bool owned);
       Isis::Camera *p_camera;  //!<The camera (if the image has a camera)
       Isis::Projection *p_projection;  //!<The projection (if the image is projected)
+      bool p_ownCameraOrProjection;
```
Comment (Kelvinrr) [inline isis/src/base/objs/UniversalGroundMap/UniversalGroundMap.h]: can you document this variable?

File: isis/src/base/objs/UniversalGroundMap/UniversalGroundMap.cpp [hunk 2]
```diff
@@ -33,34 +40,82 @@ namespace Isis {
...
+        catch(IException &error) {
+          realError.append(error);
+          throw realError;
+        }
+      }
+    }
+  }
 
-    Pvl &pvl = *cube.label();
+  void UniversalGroundMap::setProjection(Cube *cube, bool owned) {
```
Comment (Kelvinrr) [inline isis/src/base/objs/UniversalGroundMap/UniversalGroundMap.cpp]: needs a doc string as well

**Review by Kelvinrr — COMMENTED** [review]
in what contexts will the groundmap not own the pointers to camera or projection?

**Review by Kelvinrr — APPROVED** [review]
