### PR TITLE
Fixed SolarLon to compute from Table if cube is spiceinited

### LINKED ISSUE #3703: SolarLon should be computed from Table if cube is spiceinited.
**ISIS version(s) affected**: 4.X.X

**Description**  

Spice::computeSolarLon by default always computes solar lon and appends it the cube label from Spice kernels. This should use the tables if present. This is an issue when creating tables from ISDs instead of going through the spiceinit process. 

**How to reproduce**  

Run Campt on a cube that doesn't have the solor lon key present and you'll get a tiny negative number in place of real solor lon. 

**Possible Solution**  

The code already exists in Spice::computeSolarLon it just needs the if statement changed to include `if (m_usingAle || !m_usingNaif)`. This will create a subtle difference in SolorLon value so tests will need to be updated. 

**Additional context**

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

Updated existing loop in Spice::computeSolarLon so that it'll now calculate from Table when applicable. Updated tests that are affected to this change.

## Related Issue

Fixes #3703 

## Motivation and Context

Support Sprint 4/12/21

## How Has This Been Tested?

Updated tests that were once showing SolarLon as a small negative number, which was the incorrect output, to the now correctly calculated SolarLon. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
It is possible that I may have missed some tests that are affected by this code change. I will see if Jenkins outputs any test failures and update accordingly.

**Comment by amystamile-usgs** [comment]
Looks like quite a few of app and module tests need updated truth files due to slight variations in SolarLongtitude. Not sure why FunctionalTestCamdevDefault would be failing though.

**Comment by amystamile-usgs** [comment]
Determined the following failed module tests are using campt and the only change in the truth data is the SolarLongitude: 
- cassini_module_test_vims
- clementine_module_test_clementine 
- hayabusa_module_test_fullframe
- hayabusa_module_test_subframe
- hayabusa2_module_test_OncCamera
- mex_module_test_hrsc
- mgs_module_test_moc
- mro_module_test_hirise
- near_module_test_msi
- odyssey_module_test_themis
- osirisrex_module_test_mapcam

**Review by jessemapel — DISMISSED** [review]

**Comment by amystamile-usgs** [comment]
Before merging, I am going to look into why the following app tests are failing with these changes:

698 - ringspt_app_test_groundPosition (Failed)
699 - ringspt_app_test_imagePosition (Failed)
807 - deltack_app_test_directOffTarget (Failed)
808 - deltack_app_test_directVIMS (Failed)
1093 - hideal2pds_app_test_notJitterCorrected (Failed)
1174 - tgocassismos_app_test_default (Failed)
1529 - LineScannerCube.FunctionalTestCamdevDefault (Failed)

ringspt, hideal2pds, and tgocassismos all just need a tolerance added to their DIFF files for Solar Longitude since the difference is 0.0001 or less. 

deltack app tests use campt which is expected to change the Solar Longitude output. Therefore they need updated truth data.

File: isis/tests/FunctionalTestsCamdev.cpp [hunk 1]
```diff
@@ -96,8 +96,8 @@ TEST_F(LineScannerCube, FunctionalTestCamdevDefault) {
...
   }
 
-  EXPECT_NEAR(average/oCube.bandCount(), -3.3918738393628582e+306, 0.0000001);
-  EXPECT_NEAR(sum/oCube.bandCount(), 112847425994.19986, 0.0000001);
-  EXPECT_NEAR(stddev/oCube.bandCount(),-3.3918738393628582e+306, 0.0000001);
-  EXPECT_NEAR(validPixels/oCube.bandCount(), 11832.33962264151, 0.0000001);
+  EXPECT_NEAR(average/oCube.bandCount(), 9183553.1942929607, 0.0000001);
+  EXPECT_NEAR(sum/oCube.bandCount(), 112847454091.56306, 0.0000001);
+  EXPECT_NEAR(stddev/oCube.bandCount(), 11.299672545293422, 0.0000001);
+  EXPECT_NEAR(validPixels/oCube.bandCount(), 12064.188679245282, 0.0000001);
```
Comment (amystamile-usgs) [inline isis/tests/FunctionalTestsCamdev.cpp:102]: I would like someone to confirm that these changes make sense with the updates made. I am not sure how updating the SolarLongitude changes these outputs.

Comment (jessemapel) [reply isis/tests/FunctionalTestsCamdev.cpp:102]: This test generates a band that is the solar longitude at every pixel in the image. Previously this would result in a band of all NULLS, hence the average being astronomically huge, but not it doesn't.

Comment (jessemapel) [reply isis/tests/FunctionalTestsCamdev.cpp:102]: See line 70 for the argument that enables this.

**Review by jessemapel — APPROVED** [review]

**Comment by jessemapel** [comment]
@amystamile-usgs Go ahead and merge this and check in your test data when you're ready.
